"""Export a self-contained snapshot so the app can run without Postgres.

The pipeline is database-first and stays that way — the SQL layer is the
analytics engine. But a Streamlit deployment has no Postgres, and neither does
someone who has just cloned the repo and wants to look at it.

So this writes everything the app needs as files:

    data/processed/snapshot/districts.parquet    districts + percentile matrix
    data/processed/snapshot/sensitivity.parquet  Phase 4 output
    data/processed/snapshot/allocation.parquet   Phase 3 output
    data/processed/snapshot/districts.geojson    only MATCHED polygons, simplified
    data/processed/snapshot/manifest.json        provenance

The geojson is rebuilt rather than copied: the raw file is 8 MB with 735
polygons, most of which the app never draws. Keeping only matched polygons and
simplifying the geometry produces something small enough to commit, so a
deployment needs no external download.

    python -m src.snapshot
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone

import pandas as pd

from src.config import DATA_INTERIM, DATA_PROCESSED, engine, load_yaml, raw_path

SNAP = DATA_PROCESSED / "snapshot"
SIMPLIFY_TOLERANCE = 0.01     # ~1 km. Plenty for a national choropleth.


def main() -> int:
    print("=== Snapshot export ===")
    SNAP.mkdir(parents=True, exist_ok=True)
    scheme = load_yaml("indicators.yml")["default_scheme"]
    eng = engine()

    with eng.connect() as cx:
        pct = pd.read_sql("""
            select p.district_id, p.indicator_key, p.need_percentile
            from core.mv_indicator_percentile p
            where p.district_id in (select district_id from core.mv_district_score)""", cx)
        meta = pd.read_sql("""
            select distinct d.district_id, d.nfhs_state, d.nfhs_district, d.region,
                   d.terrain, d.rural_population, d.catchment_norm, d.is_apportioned
            from core.district d
            join core.mv_district_score s using (district_id)""", cx)
        sens = pd.read_sql("""
            select district_id, regime, ilp_stability, rank_stability, classification
            from core.weight_sensitivity""", cx)
        alloc = pd.read_sql("""
            select scenario, district_id, need_index, coverage_gain
            from core.allocation""", cx)

    wide = pct.pivot(index="district_id", columns="indicator_key",
                     values="need_percentile").astype(float)
    base = meta.set_index("district_id").join(wide, how="inner").reset_index()
    base.to_parquet(SNAP / "districts.parquet", index=False)
    sens.to_parquet(SNAP / "sensitivity.parquet", index=False)
    alloc.to_parquet(SNAP / "allocation.parquet", index=False)
    print(f"  districts.parquet    {len(base):,} rows x {base.shape[1]} cols")
    print(f"  sensitivity.parquet  {len(sens):,}")
    print(f"  allocation.parquet   {len(alloc):,}")

    # --- trimmed, simplified geometry ---------------------------------------
    geo_path = DATA_INTERIM / "geo_crosswalk.csv"
    if geo_path.exists():
        import geopandas as gpd
        xw = pd.read_csv(geo_path).dropna(subset=["district_id"])
        xw["district_id"] = xw.district_id.astype(int)
        g = gpd.read_file(raw_path("district_boundaries"))
        g = g[g.shapeID.isin(set(xw.shape_id))][["shapeID", "geometry"]]
        g["geometry"] = g.geometry.simplify(SIMPLIFY_TOLERANCE, preserve_topology=True)
        g = g.merge(xw[["shape_id", "district_id"]],
                    left_on="shapeID", right_on="shape_id", how="inner")
        out = SNAP / "districts.geojson"
        g[["shapeID", "district_id", "geometry"]].to_file(out, driver="GeoJSON")
        mb = out.stat().st_size / 1e6
        print(f"  districts.geojson    {len(g):,} polygons, {mb:.1f} MB "
              f"(from {raw_path('district_boundaries').stat().st_size / 1e6:.1f} MB)")
    else:
        print("  [skip] geo_crosswalk.csv missing — run `make geo` for map support")

    manifest = {
        "exported_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "scheme": scheme,
        "districts": len(base),
        "indicators": [c for c in base.columns if c in
                       {i["key"] for i in load_yaml("indicators.yml")["indicators"]}],
        "allocation_scenarios": sorted(alloc.scenario.unique().tolist()),
        "sensitivity_regimes": sorted(sens.regime.unique().tolist()) if len(sens) else [],
        "note": "Generated by src/snapshot.py from Postgres. The database remains the "
                "source of truth; this exists so the app runs without one.",
    }
    (SNAP / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"\n  snapshot -> {SNAP}")
    print("\nSNAPSHOT COMPLETE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
